function [dt,Mt] = back_0(winPt,winRect,ID,Gender,belta,Path)
%n nback
%Tr train
%Trr    number of trials
% k  speed
% a true
% l false
%%  START
% identify the environment
%
% clear
% AssertOpenGL;
% Screen('Preference', 'SkipSyncTests',1);
% Screen('Preference','VisualDebugLevel',3);
% Screen('Preference','SuppressAllWarnings',1);
%
% identify the keyboard
TimePoint = [];
Mark = [];
SubjID = [];
Mt = table(SubjID,Mark,TimePoint);
KbName('UnifyKeyNames');
escapeKey = KbName('ESCAPE');
spaceKey = KbName('Space');
aKey = KbName('a');
lKey = KbName('l');
Screen('close')
%date
Trr=40;k=1;n=0;
ID = transpose(str2double(cell2mat(ID)))*ones((Trr),1);
Gender= transpose(str2double(cell2mat(Gender)))*ones((Trr),1);

nu1=randperm(10)-1;nu1=nu1';nu2=randperm(10)-1;nu2=nu2';nu3=randperm(10)-1;nu3=nu3';nu4=randperm(10)-1;nu4=nu4';
nu2=[nu1; nu2; nu3 ;nu4];
% ID = inputdlg({'ID'},'ID',1);
% Gender= inputdlg({'Gender'},'Gender',1);

nu=nu2;
Date = repmat(datestr(now,30),(Trr),1);
Time=zeros((Trr),1);
acc=zeros((Trr),1);
dt= table(ID,Gender,Date,nu,acc,Time);

%time
t1=5*k;
t2=1*k;
t3=2*k;  %who is number
t4=1*k;
t5=1.5*k;
%% START
%train
% [winPt,winRect] = Screen('OpenWindow',0,[125,125,125]);
SC = [winRect(3),winRect(4)];
Xmax=SC(1);
Ymax=SC(2);
l1=[0 0 Xmax Ymax];


text= dt.nu;
tex=num2str(text);
p1=imread('p1.JPG');p2=imread('p2.JPG');p3=imread('p3.JPG');p4=imread('p4.JPG');p5=imread('p5.JPG');
p1= Screen('MakeTexture',winPt,p1);
p2= Screen('MakeTexture',winPt,p2);
p3= Screen('MakeTexture',winPt,p3);
p4= Screen('MakeTexture',winPt,p4);
p5= Screen('MakeTexture',winPt,p5);

HideCursor;
% Screen('DrawTextures',winPt,p1,[],l1);
% Screen('Flip',winPt);
% WaitSecs(t1);
% KbWait;

% Screen('DrawTextures',winPt,p2,[],l1);
% Screen('Flip',winPt);
% WaitSecs(t2);

Screen('TextSize',winPt, 80);
Screen('TextColor',winPt,[0 0 0]);
l2=[0.5*Xmax 0.44*Ymax];
% z=randi([1,10]);
% Screen('TextBounds', winPt, tex(z));
% Screen('DrawText',winPt,tex(z),l2(1),l2(2));
% Screen('Flip',winPt);
% Screen('FillRect',winPt,[125,125,125]);
% WaitSecs(t3);
% Screen('DrawTextures',winPt,p2,[],l1);
% Screen('Flip',winPt);
% WaitSecs(t2);
% Screen('DrawTextures',winPt,p2,[],l1);
% Screen('Flip',winPt);
% WaitSecs(t2);
% for i=1:Tr
%     [keyIsDown,secs,keyCode]=KbCheck;
%     while KbCheck;end
%     if keyCode(escapeKey) == 1
%         Screen('CloseAll');
%         break
%     end
%     Screen('TextColor',winPt,[255 255 255]);
%     Screen('TextBounds', winPt, tex(i));
%     Screen('DrawText',winPt,tex(i),l2(1),l2(2));
%     [~,SOT]=Screen('Flip',winPt);
%     Runtime = SOT+t4;
%     while GetSecs<Runtime
%         [KeyisDown,secs,keyCode] = KbCheck;
%         dt.Time(i)= secs-SOT;
%         if KeyisDown
%             if keyCode(aKey) == 1
%                 if dt.nu(i) ==text(z)
%                     dt.acc(i)= 1;
%                 else
%                     dt.acc(i)=0;
%                 end
%                 break
%             elseif keyCode(lKey) == 1
%                 if dt.nu(i) ~=text(z)
%                     dt.acc(i)= 1;
%                 else
%                     dt.acc(i)=0;
%                 end
%                 break
%             end
%         end
%     end
%     if dt.acc(i)==1
%         Screen('DrawTextures',winPt,p4,[],l1);
%     else
%         Screen('DrawTextures',winPt,p5,[],l1);
%     end
%     Screen('Flip',winPt);
%     WaitSecs(t5);
%     
%     Screen('Flip',winPt);
%     WaitSecs(t2);
%     if i==10
%         Screen('DrawTextures',winPt,p3,[],l1);
%         Screen('Flip',winPt);
%         WaitSecs(t1);
%         KbWait;
%     end
% end
%% real start
Screen('DrawTextures',winPt,p1,[],l1);
Screen('Flip',winPt);
WaitSecs(t1*k)
KbWait;
Screen('DrawTextures',winPt,p2,[],l1);
Screen('Flip',winPt);
WaitSecs(t2);
Screen('TextSize',winPt, 80);
Screen('TextColor',winPt,[0 0 0]);
l2= [0.5*Xmax 0.44*Ymax];
Rect = Screen('TextBounds', winPt, tex(5));
z=randi([1,10]);
Screen('DrawText',winPt,tex(z),l2(1),l2(2));
Screen('Flip',winPt);
Screen('FillRect',winPt,[125,125,125]);
WaitSecs(t3);
Screen('DrawTextures',winPt,p2,[],l1);
Screen('Flip',winPt);
WaitSecs(t2);
Mt(1,:)=fNIRT(1,3,ID(1));
t= 2;
for i=1:Trr
    [keyIsDown,secs,keyCode]=KbCheck;
    while KbCheck;end
    if keyCode(escapeKey) == 1
        Screen('CloseAll');
        break
    end
    Screen('TextColor',winPt,[255 255 255]);
    Rect = Screen('TextBounds', winPt, tex(i)); 
    Mt(t,:)=fNIRT(10,3,ID(1));t =t+1;
    Screen('DrawText',winPt,tex(i),l2(1),l2(2));
    [~,SOT]=Screen('Flip',winPt);
    Runtime = SOT+t4;
    ttt=0;
    while GetSecs<Runtime
        [KeyisDown,secs,keyCode] = KbCheck;
        dt.Time(i)= secs-SOT;
        if KeyisDown
            if keyCode(aKey) == 1
                if dt.nu(i) ==text(z)
                    dt.acc(i)= 1;
                    Mt(t,:)=fNIRT(11,3,ID(1));t =t+1;
                else
                    dt.acc(i)=0;
                    Mt(t,:)=fNIRT(12,3,ID(1));t =t+1;
                end
                 ttt=1;
                break
            elseif keyCode(lKey) == 1
                if dt.nu(i) ~=text(z)
                    dt.acc(i)= 1;
                    Mt(t,:)=fNIRT(11,3,ID(1));t =t+1;
                else
                    dt.acc(i)=0;
                    Mt(t,:)=fNIRT(12,3,ID(1));t =t+1;
                end
                 ttt=1;
                break
            end
        end
    end
      if ttt==0
        dt.acc(i)=0;
        Mt(t,:)=fNIRT(22,3,ID(1));t =t+1;
    end
    Screen('Flip',winPt);
    WaitSecs(t5);
    if i==0.5*Trr
        Screen('DrawTextures',winPt,p3,[],l1);
        Screen('Flip',winPt);
        WaitSecs(t1);
        KbWait;
        
        Screen('DrawTextures',winPt,p2,[],l1);
        Screen('Flip',winPt);
        WaitSecs(t2);
        
        Rect = Screen('TextBounds', winPt, tex(i));
        Screen('TextColor',winPt,[0 0 0]);
        z=randi([1,10]);
        Screen('DrawText',winPt,tex(z),l2(1),l2(2));
        Screen('Flip',winPt);
        Screen('FillRect',winPt,[125,125,125]);
        WaitSecs(t3);
        
        Screen('DrawTextures',winPt,p2,[],l1);
        Screen('Flip',winPt);
        WaitSecs(t2);
    end
end
Mt(t,:)=fNIRT(201,3,ID(1));
save([Path,'0back_',num2str(belta),'_',num2str(ID(1)),'.mat']);
% Screen('CloseAll');
